language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
notifications:
  email:
    recipients:
      - shreeharinw@gmail.com
    on_success: always
    on_failure: always
